# Generated by Django 5.2.1 on 2026-03-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_flashcards_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
