# Generated by Django 5.2.1 on 2026-03-07 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features_quiz_enabled', models.BooleanField(default=True, help_text='Enable/disable quiz feature')),
                ('features_flashcard_enabled', models.BooleanField(default=True, help_text='Enable/disable flashcard feature')),
                ('features_chat_enabled', models.BooleanField(default=True, help_text='Enable/disable chat feature')),
                ('features_materials_enabled', models.BooleanField(default=True, help_text='Enable/disable materials upload')),
                ('max_upload_size_mb', models.IntegerField(default=25, help_text='Maximum file upload size in MB')),
                ('allowed_file_types', models.TextField(default='pdf,docx,doc,txt,xlsx,xls,pptx,ppt', help_text='Comma-separated list of allowed file extensions')),
                ('default_quiz_time_limit_minutes', models.IntegerField(default=30, help_text='Default quiz time limit in minutes')),
                ('max_quiz_questions', models.IntegerField(default=100, help_text='Maximum questions per quiz')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode (blocks user access)')),
                ('maintenance_message', models.TextField(blank=True, help_text='Message shown during maintenance mode')),
                ('chatbot_daily_limit', models.IntegerField(default=0, help_text='Chat messages per user per day (0=unlimited)')),
                ('quiz_daily_limit', models.IntegerField(default=0, help_text='Quizzes per user per day (0=unlimited)')),
                ('platform_name', models.CharField(default='Lamla AI', max_length=255)),
                ('support_email', models.EmailField(blank=True, help_text='Contact email for support requests', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
    ]
