# Generated by Django 5.2.1 on 2026-03-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_quizexperiencerating'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='quizexperiencerating',
            new_name='dashboard_q_source_e6dc6a_idx',
            old_name='dashboard_qu_source_b77157_idx',
        ),
    ]
