# Generated by Django 5.2.1 on 2026-04-15 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_anonymoususageevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='anonymoususageevent',
            new_name='dashboard_a_created_b01fa0_idx',
            old_name='dashboard_a_created_0a8f31_idx',
        ),
        migrations.RenameIndex(
            model_name='anonymoususageevent',
            new_name='dashboard_a_path_45b7d4_idx',
            old_name='dashboard_a_path_8840a7_idx',
        ),
    ]
