# Generated by Django 5.2.1 on 2026-01-22 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("answer", models.TextField(default="N/A")),
                (
                    "question_type",
                    models.CharField(
                        choices=[("mcq", "Multiple Choice"), ("short", "Short Answer")],
                        default="mcq",
                        max_length=20,
                    ),
                ),
                ("options", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="QuestionCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_content_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("question_text", models.TextField(blank=True, null=True)),
                ("answer", models.TextField(blank=True, null=True)),
                (
                    "question_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("options", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(auto_now=True, db_index=True)),
                ("times_used", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="QuizSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Subject/topic of the quiz",
                        max_length=100,
                    ),
                ),
                ("total_questions", models.IntegerField(default=0)),
                ("correct_answers", models.IntegerField(default=0)),
                (
                    "score_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(default=0, help_text="Time taken in minutes"),
                ),
                (
                    "questions_data",
                    models.JSONField(
                        default=dict, help_text="Stored quiz questions and answers"
                    ),
                ),
                (
                    "user_answers",
                    models.JSONField(default=dict, help_text="User's answers"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Session",
                "verbose_name_plural": "Quiz Sessions",
                "ordering": ["-created_at"],
            },
        ),
    ]
