# Generated by Django 5.2.1 on 2026-04-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_backfill_topic_performance'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='quiztopicschedule',
            new_name='quiz_quizto_user_id_4b3b1e_idx',
            old_name='quiz_schedule_user_review_idx',
        ),
        migrations.RenameIndex(
            model_name='topicperformance',
            new_name='quiz_topicp_user_id_0c9e24_idx',
            old_name='quiz_topic_user_accuracy_idx',
        ),
    ]
